version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=AbosefenMongo2024!
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ../database/init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  # MongoDB Express - Database Admin UI
  mongo-express:
    image: mongo-express:1.0.0
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=AbosefenMongo2024!
      - ME_CONFIG_MONGODB_URL=mongodb://admin:AbosefenMongo2024!@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
      - ME_CONFIG_SITE_BASEURL=/mongo-admin/
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-very-secure-jwt-secret-key-2024-abosefen
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3003
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - auth-service
      - product-service
    networks:
      - microservices-network
    restart: unless-stopped

  # Authentication Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:AbosefenMongo2024!@mongodb:27017/abosefen-auth?authSource=admin
      - JWT_SECRET=your-very-secure-jwt-secret-key-2024-abosefen
      - JWT_EXPIRE=7d
      - JWT_REFRESH_EXPIRE=30d
      - BCRYPT_ROUNDS=12
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Product Service
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:AbosefenMongo2024!@mongodb:27017/abosefen-catalog?authSource=admin
      - IMAGE_UPLOAD_PATH=/app/uploads
      - MAX_FILE_SIZE=10MB
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - product_uploads:/app/uploads
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local
  product_uploads:
    driver: local

networks:
  microservices-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 